### ISSUE TITLE
hello.  is this smartbs/bill sahuliyat?

### ISSUE THREAD

**Issue by test2a** [KRITASUTRA/KPDCL_Mobile_App#1]
just found this repo and others, is this the official bill sahuliyat / smart bs page for j&k consumers?

i have some suggestions (i am a net metering consumer) so if this is the team working on the project, i would like to give some ideas

**Comment by AshwaniGoswami** [comment]
> just found this repo and others, is this the official bill sahuliyat / smart bs page for j&k consumers?
> 
> i have some suggestions (i am a net metering consumer) so if this is the team working on the project, i would like to give some ideas

no its not smart bs.  Feel free to share your suggestions

**Comment by test2a** [comment]
https://www.solar.com/learn/your-electric-bill-after-going-solar/

https://www.oregon.gov/energy/energy-oregon/Pages/Oregon-Solar-Dashboard.aspx


is it bill sahuliyat then? @AshwaniGoswami 

i am currently using home assistant at home. 

you should look at grafana and take ideas from those tables. the current system makes little sense to consumers

**Comment by AshwaniGoswami** [comment]
No its just a demo app not official bill sahuliyat or anything.
